/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_csc_backend_bc_leveldb_jni_LDBNative */

#ifndef _Included_org_csc_backend_bc_leveldb_jni_LDBNative
#define _Included_org_csc_backend_bc_leveldb_jni_LDBNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_init
  (JNIEnv *, jobject);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    openDB
 * Signature: (Lorg/csc/backend/bc_leveldb/api/TransactionConfig/Option;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_openDB
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    closeDB
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_closeDB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    syncPut
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_syncPut
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    syncDelete
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_syncDelete
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    syncBatchPut
 * Signature: (J[[B[[B)I
 */
JNIEXPORT jint JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_syncBatchPut
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    fastGet
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_fastGet
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_csc_backend_bc_leveldb_jni_LDBNative
 * Method:    fillGet
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_csc_backend_bc_1leveldb_jni_LDBNative_fillGet
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
